### ISSUE TITLE
Requests for sitemap.xml show in 404 monitor

### ISSUE THREAD

**Issue by DBPreston** [mikerockett/ProcessJumplinks#9]
I am using MarkupSitemapXML module, and even though http://example.com/sitemap.xml does show the sitemap, requests (from my browser and SE bots) are listed in this module's 404 Monitor.

**Comment by mikerockett** [comment]
It has something to do with the module's priority, because MarkupSitemapXML also hooks to the 404 event.

As mentioned in the forums, I do have plans to rewrite the 404 monitor and seperate it from Jumplinks (but ensuring interopability with Jumplinks) - the resulting module will be a lot more specific, and will only show 404 hits that really need to be seen. Everything else will be filed under the relevant type/category. Still working on the plans, though, so no fix for this any time soon.

However, I could get it to filter out sitemap.xml if the MarkupSitemapXML is enabled... Thoughts?

**Comment by DBPreston** [comment]
It isn't a major problem for me if this (relatively minor) issue is earmarked for attention in a future release. The site in question has just been redesigned and the page structure has changed, so what I tend to do is check on the 404s every day or so and create jumplinks for any 404s that warrant it, then clear the 404 log.

**Comment by mikerockett** [comment]
As this has come up before, I'm going to plug a hotfix for v1.5, due out in a week or so. Will also check for other modules that may clog up the log.

**Comment by mikerockett** [comment]
@DBPreston - please see above commit to the dev branch and let me know if it works for you.

**Comment by DBPreston** [comment]
That seems to have done it. Thanks, Mike. Marking this issue closed.

**Comment by mikerockett** [comment]
:+1: Glad it worked out.
